files:
  - source: /src/i18n/en/*.json
    translation: /src/i18n/%two_letters_code%/%original_file_name%
  - source: /src/i18n/locales/en/*
    translation: /src/i18n/locales/%two_letters_code%/%original_file_name%
